#!/usr/bin/env php
<?php
/**
 * Craft console bootstrap file
 */

// Turn stream logging on for the queue container
define('CRAFT_STREAM_LOG', true);
// Load shared bootstrap
require __DIR__ . '/bootstrap.php';

// Load and run Craft
/** @var craft\console\Application $app */
$app = require CRAFT_VENDOR_PATH . '/craftcms/cms/bootstrap/console.php';
$exitCode = $app->run();
exit($exitCode);
