fieldLayouts:
  44918e94-126a-4108-98da-1f66e19d2b2d:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 35aed03f-a679-4e5f-b6d1-c324bacea57a
            warning: null
            width: 100
          -
            fieldUid: 21903cb2-5b82-49ea-9766-e120d0951ea3
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c218ec6f-7d3b-4836-a62e-481537610827
            warning: null
            width: 100
        name: Content
        uid: 2dcdd6e6-2c9a-4c4e-893d-bcd2351960b1
handle: blog
hasTitleField: true
name: Blog
section: de308a7d-1794-448f-9176-29e2eace7ecf
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
