fieldLayouts:
  3079b909-ff31-4f40-98a0-10c57767ab1f:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 5bbaf848-457c-4e49-af35-8efe6f496b1c
            warning: null
            width: 100
          -
            fieldUid: 21903cb2-5b82-49ea-9766-e120d0951ea3
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 365f2cdb-a30b-436c-abc9-e0e3965455d8
            warning: null
            width: 100
        name: Content
        uid: 6db37727-e961-453c-bb48-791e87137555
handle: homepage
hasTitleField: false
name: Homepage
section: 54e60257-f31a-44aa-960e-bbd364197e28
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: none
